version: '3'
services:
  mydb:
    container_name: mydb
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  my-spring:
    image: addusername/my_api
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - mydb
    restart: always
  
  my-vue:
    image: addusername/my-view
    ports:
    - 8081:8080
    depends_on:
    - my-spring
    restart: always
    
  
  